fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.10.0  # 建议升级到最新版
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: rust
        files: \.rs$
      - id: cargo-deny
        name: cargo deny check
        entry: cargo deny check -d
        language: rust
        files: "(Cargo\\.toml|Cargo\\.lock)$"
      - id: typos
        name: typos
        language: system  # 假设已全局安装 `typos`
        entry: typos
        files: \.*$
      - id: cargo-check
        name: cargo check
        entry: cargo check --workspace
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features --tests -- -D warnings
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo nextest run --all-features --no-fail-fast
        language: rust
        files: \.rs$
        pass_filenames: false
